# Generated by Django 2.2.5 on 2019-09-27 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'default_related_name': 'answers', 'verbose_name': 'Ответ на вопрос', 'verbose_name_plural': 'Ответы на вопросы'},
        ),
        migrations.AlterModelOptions(
            name='discussion',
            options={'default_related_name': 'discussions', 'verbose_name': 'Обсуждение', 'verbose_name_plural': 'Обсуждения'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'default_related_name': 'questions', 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='questionnaire.Question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='questionnaire.Theme', verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='question',
            name='discussion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questionnaire.Discussion', verbose_name='Обсуждение'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField(verbose_name='Значение')),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='questionnaire.Discussion', verbose_name='Обсуждение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лайк|Дизлайк',
                'verbose_name_plural': 'Лайки|Дизлайки',
                'default_related_name': 'likes',
            },
        ),
    ]
