# Generated by Django 2.2.5 on 2019-09-27 13:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questionnaire', '0002_auto_20190927_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('discussion', 'user')},
        ),
    ]
