# Generated by Django 2.2.5 on 2019-09-27 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_auto_20190927_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Текст'), (2, 'Длинный текст'), (3, 'Да/Нет'), (4, 'Число'), (5, 'Один вариант ответа'), (6, 'Несколько вариантов ответа')], verbose_name='Тип вопроса'),
        ),
        migrations.CreateModel(
            name='AnswerVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(max_length=255, verbose_name='Вариант ответа')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answer_variants', to='questionnaire.Question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ на вопрос',
                'verbose_name_plural': 'Ответы на вопросы',
                'default_related_name': 'answer_variants',
            },
        ),
    ]
