# Generated by Django 2.2.5 on 2019-09-27 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questionnaire', '0005_auto_20190927_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Физ лицо'), (2, 'Юр лицо')], default=1, verbose_name='Тип'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='questionnaire.Discussion', verbose_name='Обсуждение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'default_related_name': 'comments',
            },
        ),
    ]
