# Generated by Django 2.2.5 on 2019-09-27 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0007_auto_20190927_1957'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Theme',
            new_name='Topic',
        ),
        migrations.RenameField(
            model_name='discussion',
            old_name='theme',
            new_name='topic',
        ),
    ]
