# Generated by Django 2.2.5 on 2019-09-27 17:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0008_auto_20190927_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата-время закрытия'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата-время создания'),
            preserve_default=False,
        ),
    ]
