# Generated by Django 2.2.5 on 2019-09-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0011_auto_20190928_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='preview',
            field=models.CharField(default='', max_length=100, verbose_name='Предпросмотр'),
            preserve_default=False,
        ),
    ]
