# Generated by Django 2.2.5 on 2019-09-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0012_discussion_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='name',
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Текст'), (2, 'Да/Нет'), (3, 'Число'), (4, 'Один вариант ответа'), (5, 'Несколько вариантов ответа')], verbose_name='Тип вопроса'),
        ),
    ]
