version: "3"

services:
    db:
        image: postgres:alpine
        env_file: db.env
        volumes:
            - "db:/var/lib/postgresql/pgdata"
    proxy:
      image: nginx:alpine
      volumes:
        - "./nginx.conf:/etc/nginx/nginx.conf"
        - "static:/var/www/static"
      ports:
        - 8001:8000
    backend:
        image: hack
        build:
            context: ../
            dockerfile: docker/Dockerfile
        env_file: db.env
        volumes:
          - "static:/app/static"
        environment:
          DJANGO_SETTINGS_MODULE: hack.settings_production
        depends_on:
            - db
        ports:
            - 8000:8000
    worker:
      image: hack
      build:
        context: ../
        dockerfile: docker/Dockerfile
      env_file: db.env
      environment:
        DJANGO_SETTINGS_MODULE: hack.settings_production
      depends_on:
        - db
      command: ["python", "manage.py", "qcluster"]
    vk_bot:
      image: vk_bot

volumes:
    db:
