# Generated by Django 2.2.5 on 2019-09-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Физ лицо'), (2, 'Юр лицо')], default=1, verbose_name='Тип'),
            preserve_default=False,
        ),
    ]
