# Generated by Django 2.2.5 on 2019-09-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_customuser_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Физ лицо'), (1, 'Юр лицо')], verbose_name='Тип'),
        ),
    ]
