# Generated by Django 2.2.5 on 2019-09-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190927_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(default='', max_length=150, unique=True, verbose_name='Ник'),
            preserve_default=False,
        ),
    ]
